[package]
name = "cs252chkr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chrono = "0.4.39"
chrono-humanize = "0.2.3"
clap = { version = "4.5.28", features = ["derive"] }
color-print = "0.3.7"
git2 = { version = "0.20.0", default-features = false }
sentry = "0.36.0"
thiserror = "2.0.12"
